version: "3"

services:
  neptune:
    build: 
      context: "./src/Neptune"
    environment:
      # NORMAL
      # - "NEPTUNE_API_DELAY_THRESHOLD=0"
      # - "NEPTUNE_VALUES_API_SECONDS_DELAY=0"
      # DDOS
      - "NEPTUNE_API_DELAY_THRESHOLD=1000"
      - "NEPTUNE_VALUES_API_SECONDS_DELAY=100"

  saturn:
    build: 
      context: "./src/Saturn"
    environment:
      - "NEPTUNE_API_HOST_URL=http://neptune"
      - "NEPTUNE_API_DEFAULT_SECONDS_TIMEOUT=30"
    depends_on:
      - neptune
    ports:
      - 80:80

  locust-master:
    image: raiyankamal/locust
    environment:
      - "TARGET_URL=http://saturn"
      - "LOCUST_MODE=master"
    ports:
      - 8089:8089
    volumes:
      - "./locust/locustfile.py:/locustfile.py" 
  
  locust-node:
    image: raiyankamal/locust
    environment:
      - "TARGET_URL=http://saturn"
      - "LOCUST_MODE=slave"
      - "LOCUST_MASTER_HOST=locust-master"
    volumes:
      - "./locust/locustfile.py:/locustfile.py"
    depends_on:
      - locust-master
    