apiVersion: v1
kind: Service
metadata:
  name: neptune-service
spec:
  selector:
    app: neptune
  ports:
  - name: api
    protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neptune-deployment
  labels:
    app: neptune
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neptune
  template:
    metadata:
      labels:
        app: neptune
    spec:
      containers:
      - name: neptune
        image: melkio/neptune:2019.1011.1127
        env:
        - name: NEPTUNE_API_DELAY_THRESHOLD
          value: "1000"
        - name: NEPTUNE_VALUES_API_SECONDS_DELAY
          value: "100"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: saturn-service
spec:
  selector:
    app: saturn
  ports:
  - name: api
    protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: saturn-deployment
  labels:
    app: saturn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: saturn
  template:
    metadata:
      labels:
        app: saturn
    spec:
      containers:
      - name: saturn
        image: melkio/saturn:2019.1011.1127
        env:
        - name: NEPTUNE_API_HOST_URL
          value: "http://neptune-service"
        - name: NEPTUNE_API_DEFAULT_SECONDS_TIMEOUT
          value: "30"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: locust-service
spec:
  selector:
    app: locust
  ports:
  - name: dashboard
    protocol: TCP
    port: 8089
    targetPort: 8089
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-deployment
  labels:
    app: locust
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust
  template:
    metadata:
      labels:
        app: locust
    spec:
      containers:
      - name: locust
        image: melkio/locust:2019.1011.1127
        env:
        - name: TARGET_URL
          value: "http://saturn-service"
        ports:
        - containerPort: 8089


