apiVersion: v1
kind: Service
metadata:
  name: neptune-service
spec:
  selector:
    app: neptune
  ports:
  - name: api
    protocol: TCP
    port: 80
    targetPort: 80
  - name: dashboard
    protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neptune-deployment
  labels:
    app: neptune
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neptune
  template:
    metadata:
      labels:
        app: neptune
    spec:
      containers:
      - name: neptune
        image: melkio/neptune:2019.1011.1127
        env:
        - name: ASPNETCORE_URLS
          value: http://+:5000
        - name: NEPTUNE_API_DELAY_THRESHOLD
          value: "0"
        - name: NEPTUNE_VALUES_API_SECONDS_DELAY
          value: "0"
        ports:
        - containerPort: 5000
      - name: neptune-proxy
        image: "traefik:v2.0"
        ports:
        - containerPort: 80
          name: traefik-proxy
        - containerPort: 8080
          name: traefik-ui
        volumeMounts:
        - name: traefik
          mountPath: /etc/traefik
      volumes:
        - name: traefik
          configMap:
            name: traefik
            items:
            - key: static
              path: traefik.toml
            - key: dynamic
              path: traefik-config.toml