apiVersion: v1
kind: Service
metadata:
  name: saturn-service
spec:
  selector:
    app: saturn
  ports:
  - name: api
    protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: saturn-deployment
  labels:
    app: saturn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: saturn
  template:
    metadata:
      labels:
        app: saturn
    spec:
      containers:
      - name: saturn
        image: melkio/saturn:2019.1011.1127
        env:
        - name: NEPTUNE_API_HOST_URL
          value: "http://neptune-service"
        - name: NEPTUNE_API_DEFAULT_SECONDS_TIMEOUT
          value: "30"
        ports:
        - containerPort: 80